"""Add class system models

Revision ID: 050976af66fa
Revises: 05b080a05405
Create Date: 2025-06-19 15:35:40.015668

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '050976af66fa'
down_revision = '05b080a05405'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    
    # Create class table first
    op.create_table('class',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('day_of_week', sa.Integer(), nullable=False),
    sa.Column('start_time', sa.Time(), nullable=False),
    sa.Column('end_time', sa.Time(), nullable=False),
    sa.Column('min_belt_level', sa.String(length=50), nullable=True),
    sa.Column('max_belt_level', sa.String(length=50), nullable=True),
    sa.Column('max_capacity', sa.Integer(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    
    # Create class_enrollment table
    op.create_table('class_enrollment',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('class_id', sa.Integer(), nullable=False),
    sa.Column('student_id', sa.Integer(), nullable=False),
    sa.Column('enrolled_from', sa.Date(), nullable=False),
    sa.Column('enrolled_until', sa.Date(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['class_id'], ['class.id'], ),
    sa.ForeignKeyConstraint(['student_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    
    # Create class_holiday table
    op.create_table('class_holiday',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('description', sa.String(length=200), nullable=True),
    sa.Column('is_recurring', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    
    # Now add columns to attendance table
    with op.batch_alter_table('attendance', schema=None) as batch_op:
        batch_op.add_column(sa.Column('updated_at', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('class_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('check_in_time', sa.Time(), nullable=True))
        batch_op.add_column(sa.Column('check_in_method', sa.String(length=20), nullable=True))
        batch_op.create_foreign_key('fk_attendance_class_id', 'class', ['class_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    
    # Remove foreign key and columns from attendance table
    with op.batch_alter_table('attendance', schema=None) as batch_op:
        batch_op.drop_constraint('fk_attendance_class_id', type_='foreignkey')
        batch_op.drop_column('check_in_method')
        batch_op.drop_column('check_in_time')
        batch_op.drop_column('class_id')
        batch_op.drop_column('updated_at')
    
    # Drop tables
    op.drop_table('class_holiday')
    op.drop_table('class_enrollment')
    op.drop_table('class')

    # ### end Alembic commands ### 