"""Rename sex column to gender

Revision ID: 05b080a05405
Revises: bca6f217c649
Create Date: 2025-06-19 15:09:20.925742

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '05b080a05405'
down_revision = 'bca6f217c649'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('gender', sa.String(length=10), nullable=True))
        batch_op.drop_column('sex')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('sex', sa.VARCHAR(length=10), nullable=True))
        batch_op.drop_column('gender')

    # ### end Alembic commands ###
