"""Add personal information fields

Revision ID: 3801cbd0c15c
Revises: e017c00ace72
Create Date: 2025-06-19 11:22:24.804176

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3801cbd0c15c'
down_revision = 'e017c00ace72'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('date_of_birth', sa.Date(), nullable=True))
        batch_op.add_column(sa.Column('sex', sa.String(length=10), nullable=True))
        batch_op.add_column(sa.Column('program', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('plan', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('classes', sa.String(length=10), nullable=True))
        batch_op.add_column(sa.Column('phone_number', sa.String(length=20), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('phone_number')
        batch_op.drop_column('classes')
        batch_op.drop_column('plan')
        batch_op.drop_column('program')
        batch_op.drop_column('sex')
        batch_op.drop_column('date_of_birth')

    # ### end Alembic commands ###
