"""add_updated_at_to_attendance

Revision ID: 5104a34db420
Revises: 050976af66fa
Create Date: 2025-06-19 15:53:44.704915

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5104a34db420'
down_revision = '050976af66fa'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('attendance', schema=None) as batch_op:
        batch_op.add_column(sa.Column('updated_at', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('class_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('check_in_time', sa.Time(), nullable=True))
        batch_op.add_column(sa.Column('check_in_method', sa.String(length=20), nullable=True))
        batch_op.create_foreign_key('fk_attendance_class_id', 'class', ['class_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('attendance', schema=None) as batch_op:
        batch_op.drop_constraint('fk_attendance_class_id', type_='foreignkey')
        batch_op.drop_column('check_in_method')
        batch_op.drop_column('check_in_time')
        batch_op.drop_column('class_id')
        batch_op.drop_column('updated_at')

    # ### end Alembic commands ###
