"""add_updated_at_to_attendance

Revision ID: 5104a34db420
Revises: 050976af66fa
Create Date: 2025-06-19 15:53:44.704915

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5104a34db420'
down_revision = '050976af66fa'
branch_labels = None
depends_on = None


def upgrade():
    conn = op.get_bind()
    result = conn.execute(sa.text(
        "SELECT column_name FROM information_schema.columns WHERE table_name='attendance' and column_name='updated_at'"
    ))
    if not result.fetchone():
        with op.batch_alter_table('attendance', schema=None) as batch_op:
            batch_op.add_column(sa.Column('updated_at', sa.TIMESTAMP()))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('attendance', schema=None) as batch_op:
        batch_op.drop_column('updated_at')

    # ### end Alembic commands ###
