"""Add free_class field and attendance audit table

Revision ID: 51b7aa0250a3
Revises: f26569842767
Create Date: 2025-08-06 13:23:39.354546

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '51b7aa0250a3'
down_revision = 'f26569842767'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('attendance_audit',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('attendance_id', sa.Integer(), nullable=False),
    sa.Column('action', sa.String(length=20), nullable=False),
    sa.Column('field_name', sa.String(length=50), nullable=True),
    sa.Column('old_value', sa.Text(), nullable=True),
    sa.Column('new_value', sa.Text(), nullable=True),
    sa.Column('changed_by', sa.Integer(), nullable=False),
    sa.Column('changed_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['attendance_id'], ['attendance.id'], ),
    sa.ForeignKeyConstraint(['changed_by'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('attendance', schema=None) as batch_op:
        batch_op.add_column(sa.Column('free_class', sa.Boolean(), nullable=True))

    # Check if qr_code_id column exists before trying to drop it
    connection = op.get_bind()
    inspector = sa.inspect(connection)
    columns = [col['name'] for col in inspector.get_columns('user')]
    
    if 'qr_code_id' in columns:
        with op.batch_alter_table('user', schema=None) as batch_op:
            batch_op.drop_column('qr_code_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # Check if qr_code_id column exists before trying to add it
    connection = op.get_bind()
    inspector = sa.inspect(connection)
    columns = [col['name'] for col in inspector.get_columns('user')]
    
    if 'qr_code_id' not in columns:
        with op.batch_alter_table('user', schema=None) as batch_op:
            batch_op.add_column(sa.Column('qr_code_id', sa.TEXT(), nullable=True))

    with op.batch_alter_table('attendance', schema=None) as batch_op:
        batch_op.drop_column('free_class')

    op.drop_table('attendance_audit')
    # ### end Alembic commands ###
