"""Add effective_from and effective_to fields to User model

Revision ID: bca6f217c649
Revises: 3801cbd0c15c
Create Date: 2025-06-19 15:03:25.513144

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bca6f217c649'
down_revision = '3801cbd0c15c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('effective_from', sa.Date(), nullable=True))
        batch_op.add_column(sa.Column('effective_to', sa.Date(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('effective_to')
        batch_op.drop_column('effective_from')

    # ### end Alembic commands ###
